[workspace]

members = [
    "lines",
    "day_1_cal_count",
    "day_2_rock_paper_scissors",
    "day_3_rucksack_reorg",
    "day_4_camp_cleanup",
    "day_5_supply_stacks",
    "day_6_tuning_trouble",
]
